config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'currencies#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  include HTTParty
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_global_variables
  
  def index
     
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_global_variables
     # @currency = Currency.find(params[:id])
      @global_data = HTTParty.get('https://api.coinmarketcap.com/v1/global/',
      :headers =>{'Content-Type' => 'application/json'} )
       @currencies = HTTParty.get('https://api.coinmarketcap.com/v1/ticker/?limit=0',
      :headers =>{'Content-Type' => 'application/json'} )
    end
    
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]
  
  # GET /currencies
  # GET /currencies.json
  def index
    
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
   
    currency_id = params[:id]
    
     @currency = HTTParty.get('https://api.coinmarketcap.com/v1/ticker/'+ currency_id + '/',
    :headers =>{'Content-Type' => 'application/json'} )
    
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
     # @currency = Currency.find(params[:id])
     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:id, :name, :symbol, :rank)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.text_field :rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered table-responsive">
    <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Symbol</th>
      <th>Price(USD)</th>
      <th>Price (BTC)</th>
      <th>Volume (24h)</th>
      <th>Market Cap</th>
      <th>Circulating Supply</th>
      <th>% 1h </th>
      <th>% 24h </th>
      <th>% 7d </th>
     
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= currency["rank"] %></td>
        <td><%=link_to  currency["name"], currency_path(:id => currency["id"]) %></td>
        <td><%= currency["symbol"] %></td>
        <td><%= currency["price_usd"] %></td>
        <td><%= currency["price_btc"] %></td>
        <td><%= currency["24h_volume_usd"] %></td>
        <td><%= currency["market_cap_usd"] %></td>
        <td><%= currency["available_supply"] %></td>
        <td><%= currency["percent_change_1h"] %></td>
        <td><%= currency["percent_change_24h"] %></td>
        <td><%= currency["percent_change_7d"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

  

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<div class="container-fluid currency_card_container">
  <div class="card" id="currency_card">
    <% @currency.each do |currency| %>
      <div class="card-header text-center currency_name">
       <strong><%= currency["name"] %> (<%= currency["symbol"] %>)</strong> 
       </div>
      <div class="container-fluid card-body">
        <div class="row">
          <div class="col-sm-6 text-center">
            <ul class="list">
              <li class="list-item"><strong>Price(USD)</strong></li>
              <li class="list-item"><strong>Price(BTC)</strong></li>
            </ul>
          </div>
          <div class="col-sm-6 text-center currency_values">
             <ul class="list">
              <li class="list-item"><strong>$<%= currency["price_usd"] %> ( <%= currency["percent_change_24h"] %> %)</strong> </li>
              <li class="list-item"><strong><%= currency["price_btc"] %></strong></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 text-center">
            <table class="table table-bordered table-responsive">
               <thead>
                <tr>
                  <th>Rank</th>
                  <th>Market Cap</th>
                  <th>Volume (24H )</th>
                  <th>Circulating Supply</th>
                  <th>Maximum Supply </th>
                  <th>Percentage change (1H) </th>
                  <th>Percentage change  (7D) </th>
                  <th>Last Updated </th>
                  
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= currency["rank"] %></td>
                  <td><%= currency["market_cap_usd"] %></td>
                  <td> <%= currency["24h_volume_usd"] %></td>
                  <td><%= currency["available_supply"] %></td>
                  <td><%= currency["total_supply"] %></td>
                  <td>  <%= currency["percent_change_1h"] %></td>
                  <td><%= currency["percent_change_7d"] %></td>
                  <td> <%= currency["last_updated"] %></td>
                  
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div> 
      <div class="card-footer"><%= link_to 'Back', currencies_path %></div>
    <% end %>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoCurrencyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" %>
   
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top" id="crypto_navbar">
      <div class="container-fluid crypto_currency_container">
        <div class = "row">
          <div class = "col-sm-4">
            <ul class="list-inline">
              <li class="list-inline-item">Cryptocurrencies : 
                <strong><%= @currencies.count %></strong>
              </li>
              <li class="list-inline-item">/ Markets : 
                <strong><%= @global_data["active_markets"] %></strong>
              </li>
            </ul>
          </div>
          <div class = "col-sm-8 text-right">
            <ul class="list-inline">
              <li class="list-inline-item">Market Cap : <strong><%= @global_data["total_market_cap_usd"] %></strong></li>
              <li class="list-inline-item">/ 24h Volume : <strong><%= @global_data["total_24h_volume_usd"] %></strong></li>
              <li class="list-inline-item">/ BTC Dominance : <strong><%= @global_data["bitcoin_percentage_of_market_cap"] %></strong></li>
            </ul>
          </div>
        </div>
  </div>
</header>
<div class="row crypto_heading_container">
  <div class="col-sm-12 text-center">
    <div class="crypto_title">
      <strong>Cryptocurrency Market Capitalizations</strong>
    </div>
  </div>
</div>
<hr class="title_divider">
    <div class="container-fluid currency_main_container">
  <%= yield %>
</div>
  </body>
</html>